### ISSUE TITLE
Question about Add ability to log metrics to WandB

### ISSUE THREAD

**Issue by ygean** [Storia-AI/image-eval#13]
Hi @iuliaturc,
I noticed in the RoadMap section that there is a mention of adding the capability to log metrics to Weights & Biases (W&B). I am quite interested in understanding how W&B can be utilized for tasks such as image-eval. Could you please describe the typical usage scenario for this feature?

**Comment by iuliaturc** [comment]
Closing as obsolete, removed plans to integrate with wandb for now.
