### ISSUE TITLE
cannot download human preference score

### ISSUE THREAD

**Issue by vegaluisjose** [Storia-AI/image-eval#8]
Hi Mihail,

Great idea!

I was trying to give it a shot but when I tried to download the "human preference score" model I got an error. I am attaching a screenshot.

![Screenshot 2023-09-15 at 12 46 21 PM](https://github.com/Storia-AI/image-eval/assets/2478335/15297053-e6a7-480c-b285-db6992a85ddd)

**Comment by mihail911** [comment]
thanks for your interest @vegaluisjose! I just landed a PR that should resolve this problem. Let me know if you still run into any issues! https://github.com/Storia-AI/image-eval/pull/9
